folder = [
    "720p50_mobcal_ter.yuv",
    "720p50_parkrun_ter.yuv", 
    "720p50_shields_ter.yuv",
    "720p5994_stockholm_ter.yuv",
    "FourPeople_1280x720_60.yuv",
    "KristenAndSara_1280x720_60.yuv",
    "akiyo_cif.yuv",
    "blue_sky_1080p25.yuv",
    "bowing_qcif.yuv",
    "bridge_close_cif.yuv",
    "bus_cif.yuv",
    "carphone_qcif.yuv",
    "city_cif.yuv",
    "claire_qcif.yuv",
    "coastguard_cif.yuv",
    "container_cif.yuv",
    "crew_cif.yuv",
    "deadline_cif.yuv",
    "ducks_take_off_420_720p50.yuv",
    "flower_cif.yuv",
    "football_sif.yuv",
    "foreman_cif.yuv",
    "garden_sif.yuv",
    "grandma_qcif.yuv",
    "hall_monitor_cif.yuv",
    "harbour_4cif.yuv",
    "highway_qcif.yuv",
    "husky_cif.yuv",
    "ice_4cif.yuv",
    "in_to_tree_420_720p50.yuv",
    "mad900_cif.yuv",
    "miss_am_qcif.yuv",
    "mobile_cif.yuv",
    "mother_daughter_cif.yuv",
    "mthr_dotr_qcif.yuv",
    "news_cif.yuv",
    "old_town_cross_420_720p50.yuv",
    "pamphlet_cif.yuv",
    "paris_cif.yuv",
    "park_joy_420_720p50.yuv",
    "riverbed_1080p25.yuv",
    "salesman_qcif.yuv",
    "sign_irene_cif.yuv",
    "silent_cif.yuv",
    "sintel_trailer_2k_480p24.yuv",
    "soccer_4cif.yuv",
    "station2_1080p25.yuv",
    "students_cif.yuv",
    "suzie_qcif.yuv",
    "tempete_cif.yuv",
    "tennis_sif.yuv",
    "trevor_qcif.yuv",
    "tt_sif.yuv",
    "waterfall_cif.yuv"
]

downloaded = [
    "720p50_mobcal_ter.yuv",
    "720p50_parkrun_ter.yuv",
    "720p50_shields_ter.yuv",
    "720p5994_stockholm_ter.yuv",
    "FourPeople_1280x720_60.yuv",
    "KristenAndSara_1280x720_60.yuv",
    "akiyo_cif.yuv",
    "blue_sky_1080p25.yuv",
    "bowing_qcif.yuv",
    "bridge_close_cif.yuv",
    "bus_cif.yuv",
    "carphone_qcif.yuv",
    "city_cif.yuv",
    "claire_qcif.yuv",
    "coastguard_cif.yuv",
    "container_cif.yuv",
    "crew_cif.yuv",
    "deadline_cif.yuv",
    "ducks_take_off_420_720p50.yuv",
    "flower_cif.yuv",
    "football_sif.yuv",
    "foreman_cif.yuv",
    "garden_sif.yuv",
    "grandma_qcif.yuv",
    "hall_monitor_cif.yuv",
    "harbour_4cif.yuv",
    "highway_qcif.yuv",
    "husky_cif.yuv",
    "ice_4cif.yuv",
    "in_to_tree_420_720p50.yuv",
    "mad900_cif.yuv",
    "miss_am_qcif.yuv",
    "mobile_cif.yuv",
    "mother_daughter_cif.yuv",
    "mthr_dotr_qcif.yuv",
    "news_cif.yuv",
    "old_town_cross_420_720p50.yuv",
    "pamphlet_cif.yuv",
    "paris_cif.yuv",
    "park_joy_420_720p50.yuv",
    "riverbed_1080p25.yuv",
    "salesman_qcif.yuv",
    "sign_irene_cif.yuv",
    "silent_cif.yuv",
    "sintel_trailer_2k_480p24.yuv",
    "soccer_4cif.yuv",
    "station2_1080p25.yuv",
    "students_cif.yuv",
    "suzie_qcif.yuv",
    "tempete_cif.yuv",
    "tennis_sif.yuv",
    "trevor_qcif.yuv",
    "tt_sif.yuv",
    "waterfall_cif.yuv",
]

# Sprawdź które pliki są w downloaded ale nie w folder
print("Files in downloaded but not in folder:")
for video in downloaded:
    if video not in folder:
        print(f"❌ {video}")

# Sprawdź które pliki są w folder ale nie w downloaded  
print("\nFiles in folder but not in downloaded:")
for video in folder:
    if video not in downloaded:
        print(f"➕ {video}")

# Sprawdź czy listy są identyczne
if set(folder) == set(downloaded):
    print("\n✅ Lists are identical!")
else:
    print(f"\n⚠️  Lists differ. Folder has {len(folder)} items, downloaded has {len(downloaded)} items")